server {
    listen 80;
    server_name YOUR_EC2_PUBLIC_IP_OR_DOMAIN; # Weka IP au Domain yako hapa

    # 1. FRONTEND VITE SPA (Static Files)
    root /var/www/kilimostore/frontend/dist;
    index index.html;

    client_max_body_size 50M;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. BACKEND LARAVEL API & STORAGE
    location /api {
        alias /var/www/kilimostore/backend/public;
        try_files $uri $uri/ @laravel;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/kilimostore/backend/public/index.php;
            fastcgi_pass unix:/var/run/php/php8.4-fpm.sock; # au php-fpm kulingana na toleo
        }
    }

    location @laravel {
        rewrite ^/api/(.*)$ /api/index.php?/$1 last;
    }

    # Direct PHP processing for backend public
    location ~ ^/backend/public/(.*\.php)$ {
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/kilimostore/backend/public/$1;
        include fastcgi_params;
    }

    # Prevent access to hidden files (.env, .git)
    location ~ /\. {
        deny all;
    }

    error_log  /var/log/nginx/kilimostore_error.log;
    access_log /var/log/nginx/kilimostore_access.log;
}
